#! /bin/sh
#
# This file builds and publish the Helm charts for the tools.
#
HELM="./linux-amd64/helm"
charts="helm"
repository="docs/charts"

# Install helm
if [ ! -f $HELM ]
then
  echo "Installing helm binary ..."
  curl -o helm-v3.2.1-linux-amd64.tar.gz https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
  tar -xvzf helm-v3.2.1-linux-amd64.tar.gz
fi

# Create all chart packages availables
echo "Generating chart packages ..."
for chart in ${charts}/*
do
  $HELM package $chart
done

# Move charts and recreate the index
echo "Populating repository ..."
[[ -d $repository ]] || mkdir -p $repository
mv *.tgz $repository

echo "Generating chart index ..."
$HELM repo index $repository
